### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by zeebo** [zeebo/goof#2]
microsoft shouldn't be immune to these shenanigans.

**Comment by aarzilli** [comment]
You should be able to get the path to the executable in a system independent way using `os.Executable` (go 1.8). For Windows you just need to call `debug/pe.Open` then `debug/pe.(*File).DWARF`.

**Comment by zeebo** [comment]
Oh nice. I didn't know that function existed. That can probably clean up the linux/macos support too.
